const u = "https://share.google/vCD4kQc8elUleD1EE", g = {
  CV13: { lat: 52.6247, lng: -1.4014 },
  LE67: { lat: 52.7233, lng: -1.3683 },
  LE65: { lat: 52.7471, lng: -1.4721 },
  LE11: { lat: 52.7721, lng: -1.2062 },
  LE12: { lat: 52.7291, lng: -1.1492 },
  LE6: { lat: 52.658, lng: -1.229 },
  LE3: { lat: 52.6341, lng: -1.1891 },
  LE7: { lat: 52.6841, lng: -1.0941 },
  DE14: { lat: 52.8061, lng: -1.6312 },
  DE13: { lat: 52.8251, lng: -1.6541 },
  DE15: { lat: 52.7911, lng: -1.6021 },
  DE11: { lat: 52.7731, lng: -1.5591 },
  DE73: { lat: 52.8391, lng: -1.4241 },
  DE74: { lat: 52.8381, lng: -1.3391 },
  B77: { lat: 52.6181, lng: -1.6691 },
  B79: { lat: 52.6481, lng: -1.6891 },
  CV9: { lat: 52.5781, lng: -1.5421 },
  DE12: { lat: 52.7121, lng: -1.5421 }
};
function y(o) {
  let a = 0;
  for (let n = 0; n < o.length; n++)
    a = (a << 5) - a + o.charCodeAt(n), a |= 0;
  return Math.abs(a);
}
function e(o) {
  const a = o.postcodes[0] ? o.postcodes[0].split(" ")[0] : "CV13", n = o.housingTypes ? o.housingTypes[0].toLowerCase() : "mix of residential properties", d = o.commonProblems ? o.commonProblems[0].toLowerCase() : "emergency boiler lockouts and main drain blockages", l = o.heatingTypes ? o.heatingTypes[0].toLowerCase() : "gas combi and unvented heating systems", s = o.soilType ? o.soilType.toLowerCase() : "heavy local clay ground structures", h = o.hubTown || "Market Bosworth", m = g[a] || { lat: 52.6247, lng: -1.4014 }, p = o.metaTitle || `24/7 Emergency Plumber in ${o.name} (${o.postcodes.join(", ")}) | 60-90 Min Arrival`, c = o.metaDescription || `Local 24/7 emergency plumbing & drainage services in ${o.name}. Rapid response for burst pipes, blocked toilets & boiler failures. Call ${o.phone} now.`, i = y(o.name) % 3;
  let t = [];
  i === 0 ? t = [
    `Our 24/7 emergency response units operate continuously across ${o.name}, specifically equipped to address the structural demands of the local network. With a high density of ${n} situated along ${o.road} and neighboring streets, our engineers frequently resolve acute faults such as ${d}.`,
    `We maintain rapid dispatch windows throughout the ${o.postcodes[0]} area by stationing mobile engineering teams near ${o.landmark}. Whether handling system pressure drops in ${l} or unblocking subsoil lines affected by ${s}, our teams deliver permanent isolation and repair solutions.`
  ] : i === 1 ? t = [
    `When urgent plumbing or drainage failures occur in ${o.name}, local residents benefit from our direct rapid-deployment service. Operating routinely past ${o.landmark}, our vans carry full inventory to resolve ${d} on the first visit across ${o.road} and surrounding developments.`,
    `Properties within the ${o.postcodes.join("/")} sector feature a diverse operational mix of ${n}. Ground shifts caused by ${s} often compromise underground drainage—our team uses non-destructive high-pressure water jetting and CCTV surveying to restore full flow capacity.`
  ] : t = [
    `Securing fast emergency plumbing coverage in ${o.name} is essential when facing sudden pipe ruptures or drainage backups. Our G3-certified engineers cover the ${o.postcodes[0]} district around the clock, prioritizing urgent callouts near ${o.landmark} and the broader ${o.road} corridor.`,
    `Due to local conditions characterized by ${s}, infrastructure in ${o.name} requires precise diagnostic care. From resolving limescale scaling in modern ${l} to clear severe blockage points in ${n}, we guarantee 60-minute emergency arrival times.`
  ];
  const k = [
    {
      question: `How fast can an emergency plumber arrive in ${o.name}?`,
      answer: `We maintain active response units near ${o.landmark}, allowing an average arrival time of 60 to 90 minutes for emergency callouts across ${o.name} and the ${o.postcodes.join(", ")} postcode area.`
    },
    {
      question: `Do you provide 24/7 drain jetting and toilet unblocking in ${o.name}?`,
      answer: "Yes. Our engineers carry high-pressure jetting units and specialized CCTV drain inspection cameras to clear severe main drain blockages, blocked toilets, and root ingress instantly."
    }
  ];
  return {
    name: o.name,
    phone: o.phone,
    landmark: o.landmark,
    road: o.road,
    postcodes: o.postcodes,
    description: o.description || `24/7 emergency plumbing, heating, and drainage services across ${o.name} (${o.postcodes.join(", ")}). Rapid 60-90 minute local deployment.`,
    mapSrc: o.mapSrc || u,
    housingTypes: o.housingTypes || ["Victorian Terraces", "Suburban Semi-Detached Properties", "Modern Housing Developments"],
    commonProblems: o.commonProblems || ["Hard water limescale scaling", "Boiler baseline pressure loss", "Blocked localized external grid networks"],
    drainageTypes: o.drainageTypes || ["Vitrified Clay Infrastructure Tracks", "Modern High-Flow PVC Radial Systems"],
    heatingTypes: o.heatingTypes || ["High-Efficiency Condensing Combi Boilers", "Traditional Flow Unvented Systems"],
    propertyAgeProfile: o.propertyAgeProfile || "Mixed residential stock spanning historic cores to late-20th-century expansions.",
    commercialAreas: o.commercialAreas || [`${o.name} High Street Outlets`, "Local Corporate Trade Hubs"],
    nearbyAreas: o.nearbyAreas || [h, "Surrounding District Commuter Arteries"],
    nearbyVillages: o.nearbyVillages || ["market-bosworth", "barlestone", "stoke-golding", "twycross"],
    waterPressureNotes: o.waterPressureNotes || "Maintains high baseline structural parameters across the central sector.",
    soilType: o.soilType || "Heavy localized clay structures.",
    floodRisk: o.floodRisk || "Low overall risk profile.",
    insuranceNotes: o.insuranceNotes || "Trace and access tracking documentation provided seamlessly for policy validation.",
    typicalCallouts: o.typicalCallouts || ["Emergency fluid isolation", "Main structural drain descaling", "Combi boiler flame diagnostics"],
    authorityParagraphs: o.authorityParagraphs || t,
    metaTitle: p,
    metaDescription: c,
    geoCoordinates: o.geoCoordinates || m,
    hubTown: h,
    customFAQ: o.customFAQ || k
  };
}
const b = {
  // ==========================================
  // === ALL 220 SITEMAP LOCATIONS (A-Z) ======
  // ==========================================
  "albert-village": e({ name: "Albert Village", phone: "01530 654062", landmark: "Albert Village Lake", road: "Occupation Road", postcodes: ["DE11 9"] }),
  alvaston: e({ name: "Alvaston", phone: "01332 806148", landmark: "Alvaston Park", road: "London Road", postcodes: ["DE73 8"] }),
  ambaston: e({ name: "Ambaston", phone: "01332 806148", landmark: "Ambaston Lane", road: "Ambaston Lane", postcodes: ["DE73 8"] }),
  amington: e({ name: "Amington", phone: "01827 802163", landmark: "Amington Hall", road: "Amington Road", postcodes: ["B77 1"] }),
  ansley: e({ name: "Ansley", phone: "01827 802163", landmark: "St Laurence Church", road: "Birmingham Road", postcodes: ["CV9 2"] }),
  anslow: e({ name: "Anslow", phone: "01283 890215", landmark: "The Bell Inn", road: "Main Road", postcodes: ["DE13 9"] }),
  anstey: e({ name: "Anstey", phone: "01164 105069", landmark: "The Nook", road: "Bradgate Road", postcodes: ["LE6 0"] }),
  "appleby-magna": e({ name: "Appleby Magna", phone: "01530 654062", landmark: "Sir John Moore Foundation", road: "Top Street", postcodes: ["DE12 7"] }),
  "appleby-parva": e({ name: "Appleby Parva", phone: "01530 654062", landmark: "Appleby Inn", road: "A444", postcodes: ["DE12 7"] }),
  arley: e({ name: "Arley", phone: "01827 802163", landmark: "Arley Community Centre", road: "Gun Hill", postcodes: ["CV9 2"] }),
  "ashby-de-la-zouch": e({ name: "Ashby de la Zouch", phone: "01530 654062", landmark: "Ashby Castle", road: "Market Street", postcodes: ["LE65 1", "LE65 2"] }),
  astley: e({ name: "Astley", phone: "01827 802163", landmark: "Astley Castle", road: "Astley Lane", postcodes: ["CV9 2"] }),
  "aston-on-trent": e({ name: "Aston on Trent", phone: "01332 806148", landmark: "Aston Hall", road: "Derby Road", postcodes: ["DE73 8"] }),
  atherstone: e({ name: "Atherstone", phone: "01827 802163", landmark: "Atherstone Market Square", road: "Long Street", postcodes: ["CV9 1"] }),
  austrey: e({ name: "Austrey", phone: "01827 802163", landmark: "The Bird in Hand", road: "Main Road", postcodes: ["B79 0"] }),
  "baddesley-ensor": e({ name: "Baddesley Ensor", phone: "01827 802163", landmark: "Baddesley Common", road: "New Street", postcodes: ["CV9 2"] }),
  bagworth: e({ name: "Bagworth", phone: "01530 654062", landmark: "Bagworth Heath Woods", road: "Station Road", postcodes: ["LE67 1"] }),
  "bardon-hill": e({ name: "Bardon Hill", phone: "01530 654062", landmark: "Bardon Truck Park", road: "Beveridge Lane", postcodes: ["LE67 1"] }),
  barkby: e({ name: "Barkby", phone: "01164 105069", landmark: "The Malt Shovel", road: "Main Street", postcodes: ["LE7 3"] }),
  "barkby-thorpe": e({ name: "Barkby Thorpe", phone: "01164 105069", landmark: "Barkby Thorpe Hall", road: "King Street", postcodes: ["LE7 3"] }),
  barlestone: e({ name: "Barlestone", phone: "01455 244 706", landmark: "St Giles Church", road: "Main Street", postcodes: ["CV13 0"] }),
  "barrow-upon-soar": e({ name: "Barrow upon Soar", phone: "01509 642158", landmark: "The Navigation Inn", road: "High Street", postcodes: ["LE12 8"] }),
  "barrow-upon-trent": e({ name: "Barrow upon Trent", phone: "01332 806148", landmark: "St Wilfrid's Church", road: "Sinfin Lane", postcodes: ["DE73 8"] }),
  "barton-in-the-beans": e({ name: "Barton in the Beans", phone: "01455 244 706", landmark: "The Baptist Chapel", road: "Main Street", postcodes: ["CV13 0"] }),
  "barton-under-needwood": e({ name: "Barton under Needwood", phone: "01283 890215", landmark: "Barton Marina", road: "Main Street", postcodes: ["DE13 8"] }),
  battram: e({ name: "Battram", phone: "01530 654062", landmark: "Battram Woods", road: "Wood Road", postcodes: ["LE67 1"] }),
  baxterley: e({ name: "Baxterley", phone: "01827 802163", landmark: "The Rose & Crown", road: "Main Road", postcodes: ["CV9 2"] }),
  belton: e({ name: "Belton", phone: "01509 642158", landmark: "The George Hotel", road: "Market Place", postcodes: ["LE12 9"] }),
  bentley: e({ name: "Bentley", phone: "01827 802163", landmark: "Bentley Woods", road: "Bentley Common", postcodes: ["CV9 2"] }),
  bilstone: e({ name: "Bilstone", phone: "01455 244 706", landmark: "Bilstone House", road: "Gibbet Lane", postcodes: ["CV13 0"] }),
  birstall: e({ name: "Birstall", phone: "01164 105069", landmark: "Watermead Country Park", road: "Sibson Road", postcodes: ["LE4 4"] }),
  blackfordby: e({ name: "Blackfordby", phone: "01530 654062", landmark: "The Black Lion", road: "Main Street", postcodes: ["DE11 8"] }),
  bolehall: e({ name: "Bolehall", phone: "01827 802163", landmark: "Bolehall Swifts Club", road: "Amington Road", postcodes: ["B77 3"] }),
  botcheston: e({ name: "Botcheston", phone: "01164 105069", landmark: "The Greyhound", road: "Main Street", postcodes: ["LE9 9"] }),
  "boulton-moor": e({ name: "Boulton Moor", phone: "01332 806148", landmark: "Boulton Moor Woods", road: "Chellaston Lane", postcodes: ["DE73 5"] }),
  boundary: e({ name: "Boundary", phone: "01530 654062", landmark: "Ashby Road", road: "Ashby Road", postcodes: ["DE11 7"] }),
  branston: e({ name: "Branston", phone: "01283 890215", landmark: "Branston Water Park", road: "Main Street", postcodes: ["DE14 3"] }),
  braunstone: e({ name: "Braunstone", phone: "01164 105069", landmark: "Braunstone Park", road: "Braunstone Way", postcodes: ["LE3 1"] }),
  "breedon-on-the-hill": e({ name: "Breedon on the Hill", phone: "01530 654062", landmark: "The Priory Church", road: "Ashby Road", postcodes: ["DE73 8"] }),
  bretby: e({ name: "Bretby", phone: "01283 890215", landmark: "Bretby Hall", road: "Ashby Road", postcodes: ["DE15 0"] }),
  burnaston: e({ name: "Burnaston", phone: "01283 890215", landmark: "Toyota Manufacturing UK", road: "Burnaston Lane", postcodes: ["DE65 6"] }),
  "burton-on-the-wolds": e({ name: "Burton on the Wolds", phone: "01509 642158", landmark: "The Greyhound Inn", road: "Melton Road", postcodes: ["LE12 5"] }),
  "burton-upon-trent": e({ name: "Burton upon Trent", phone: "01283 890215", landmark: "The National Brewery Centre", road: "High Street", postcodes: ["DE14 1"] }),
  cadeby: e({ name: "Cadeby", phone: "01455 244 706", landmark: "Cadeby Hall", road: "Main Street", postcodes: ["CV13 0"] }),
  caldecote: e({ name: "Caldecote", phone: "01827 802163", landmark: "Caldecote Hall", road: "Weddington Road", postcodes: ["CV10 0"] }),
  carlton: e({ name: "Carlton", phone: "01455 244 706", landmark: "The Gate Hangs Well", road: "Main Street", postcodes: ["CV13 0"] }),
  "castle-donington": e({ name: "Castle Donington", phone: "01509 642158", landmark: "Donington Park", road: "High Street", postcodes: ["DE74 2"] }),
  "castle-gresley": e({ name: "Castle Gresley", phone: "01283 890215", landmark: "Gresley Old Hall", road: "Burton Road", postcodes: ["DE11 9"] }),
  cauldwell: e({ name: "Cauldwell", phone: "01283 890215", landmark: "Cauldwell Hall", road: "Main Street", postcodes: ["DE12 6"] }),
  charley: e({ name: "Charley", phone: "01530 654062", landmark: "Mount St Bernard Abbey", road: "Abbey Road", postcodes: ["LE67 4"] }),
  chellaston: e({ name: "Chellaston", phone: "01332 806148", landmark: "The Bonnie Prince", road: "Swarkestone Road", postcodes: ["DE73 6"] }),
  "church-broughton": e({ name: "Church Broughton", phone: "01283 890215", landmark: "St Michael's Church", road: "Main Street", postcodes: ["DE65 5"] }),
  "church-gresley": e({ name: "Church Gresley", phone: "01283 890215", landmark: "Maurice Lea Memorial Park", road: "Market Street", postcodes: ["DE11 9"] }),
  "clifton-campville": e({ name: "Clifton Campville", phone: "01827 802163", landmark: "St Andrew's Church", road: "Main Street", postcodes: ["B79 0"] }),
  coalville: e({ name: "Coalville", phone: "01530 654062", landmark: "the Clock Tower", road: "Memorial Square", postcodes: ["LE67 3", "LE67 4"] }),
  coleorton: e({ name: "Coleorton", phone: "01530 654062", landmark: "Coleorton Hall", road: "The Moorlands", postcodes: ["LE67 8"] }),
  congerstone: e({ name: "Congerstone", phone: "01455 244 706", landmark: "The Horse & Jockey", road: "Shadowlane", postcodes: ["CV13 0"] }),
  "copt-oak": e({ name: "Copt Oak", phone: "01530 654062", landmark: "The Copt Oak Pub", road: "Whitwick Road", postcodes: ["LE67 9"] }),
  cossington: e({ name: "Cossington", phone: "01509 642158", landmark: "The Royal Oak", road: "Main Street", postcodes: ["LE7 4"] }),
  cotes: e({ name: "Cotes", phone: "01509 642158", landmark: "Cotes Mill", road: "Nottingham Road", postcodes: ["LE12 5"] }),
  "coton-in-the-elms": e({ name: "Coton in the Elms", phone: "01283 890215", landmark: "The Black Horse", road: "Church Street", postcodes: ["DE12 8"] }),
  cropston: e({ name: "Cropston", phone: "01164 105069", landmark: "Cropston Reservoir", road: "Station Road", postcodes: ["LE7 7"] }),
  dadlington: e({ name: "Dadlington", phone: "01455 244 706", landmark: "The Dog & Hedgehog", road: "The Green", postcodes: ["CV13 0"] }),
  "dalbury-lees": e({ name: "Dalbury Lees", phone: "01283 890215", landmark: "The Cow Dalbury", road: "The Green", postcodes: ["DE6 5"] }),
  desford: e({ name: "Desford", phone: "01164 105069", landmark: "Bosworth Academy", road: "High Street", postcodes: ["LE9 9"] }),
  diseworth: e({ name: "Diseworth", phone: "01509 642158", landmark: "Diseworth Heritage Centre", road: "Hall Gate", postcodes: ["DE74 2"] }),
  "donington-le-heath": e({ name: "Donington le Heath", phone: "01530 654062", landmark: "The Manor House", road: "Manor Road", postcodes: ["LE67 2"] }),
  donisthorpe: e({ name: "Donisthorpe", phone: "01530 654062", landmark: "Donisthorpe Woodland Park", road: "Church Street", postcodes: ["DE12 7"] }),
  dordon: e({ name: "Dordon", phone: "01827 802163", landmark: "Dordon Hall", road: "Long Street", postcodes: ["B78 1"] }),
  dosthill: e({ name: "Dosthill", phone: "01827 802163", landmark: "Dosthill Quarry", road: "Dosthill Road", postcodes: ["B77 1"] }),
  "drayton-bassett": e({ name: "Drayton Bassett", phone: "01827 802163", landmark: "Drayton Manor Park", road: "Drayton Lane", postcodes: ["B78 3"] }),
  "east-goscote": e({ name: "East Goscote", phone: "01164 105069", landmark: "The Plough", road: "Merchants Common", postcodes: ["LE7 3"] }),
  "east-leake": e({ name: "East Leake", phone: "01509 642158", landmark: "St Mary's Church", road: "Main Street", postcodes: ["LE12 6"] }),
  edingale: e({ name: "Edingale", phone: "01827 802163", landmark: "The Black Horse", road: "Pessall Lane", postcodes: ["B79 9"] }),
  egginton: e({ name: "Egginton", phone: "01283 890215", landmark: "Egginton Hall", road: "Duck Street", postcodes: ["DE65 6"] }),
  elford: e({ name: "Elford", phone: "01827 802163", landmark: "Elford Walled Gardens", road: "Church Road", postcodes: ["B79 9"] }),
  ellistown: e({ name: "Ellistown", phone: "01530 654062", landmark: "South Leicestershire College", road: "Beveridge Lane", postcodes: ["LE67 1"] }),
  elvaston: e({ name: "Elvaston", phone: "01332 806148", landmark: "Elvaston Castle", road: "Borrowash Road", postcodes: ["DE72 3"] }),
  etwall: e({ name: "Etwall", phone: "01283 890215", landmark: "John Port Academy", road: "Main Street", postcodes: ["DE65 6"] }),
  fazeley: e({ name: "Fazeley", phone: "01827 802163", landmark: "Fazeley Junction", road: "Lichfield Street", postcodes: ["B78 3"] }),
  "fenny-drayton": e({ name: "Fenny Drayton", phone: "01455 244 706", landmark: "George Fox Monument", road: "Drayton Lane", postcodes: ["CV13 0"] }),
  "field-head": e({ name: "Field Head", phone: "01164 105069", landmark: "The Field Head Hotel", road: "Markfield Road", postcodes: ["LE67 9"] }),
  findern: e({ name: "Findern", phone: "01332 806148", landmark: "Findern Green", road: "Main Street", postcodes: ["DE65 6"] }),
  foremark: e({ name: "Foremark", phone: "01332 806148", landmark: "Foremark Reservoir", road: "Milton Road", postcodes: ["DE65 6"] }),
  glascote: e({ name: "Glascote", phone: "01827 802163", landmark: "Glascote Basin", road: "Glascote Road", postcodes: ["B77 2"] }),
  glenfield: e({ name: "Glenfield", phone: "01164 105069", landmark: "Leicestershire County Council HQ", road: "Station Road", postcodes: ["LE3 8"] }),
  "great-wilne": e({ name: "Great Wilne", phone: "01332 806148", landmark: "St Chad's Church", road: "Wilne Lane", postcodes: ["DE72 2"] }),
  grendon: e({ name: "Grendon", phone: "01827 802163", landmark: "Grendon Community Centre", road: "Watling Street", postcodes: ["CV9 2"] }),
  griffydam: e({ name: "Griffydam", phone: "01530 654062", landmark: "The Griffin Inn", road: "Top Road", postcodes: ["LE67 8"] }),
  groby: e({ name: "Groby", phone: "01164 105069", landmark: "Groby Pool", road: "Leicester Road", postcodes: ["LE6 0"] }),
  harlaston: e({ name: "Harlaston", phone: "01827 802163", landmark: "The White Lion", road: "Main Road", postcodes: ["B79 9"] }),
  hartshorne: e({ name: "Hartshorne", phone: "01283 890215", landmark: "The Admiral Rodney", road: "Main Street", postcodes: ["DE11 7"] }),
  hathern: e({ name: "Hathern", phone: "01509 642158", landmark: "The Anchor Inn", road: "Loughborough Road", postcodes: ["LE12 5"] }),
  hatton: e({ name: "Hatton", phone: "01283 890215", landmark: "Tutbury and Hatton Station", road: "Station Road", postcodes: ["DE65 5"] }),
  haunton: e({ name: "Haunton", phone: "01827 802163", landmark: "St Michael's Church", road: "Main Road", postcodes: ["B79 9"] }),
  heather: e({ name: "Heather", phone: "01530 654062", landmark: "Sence Valley", road: "Swepstone Road", postcodes: ["LE67 6"] }),
  hemington: e({ name: "Hemington", phone: "01509 642158", landmark: "Hemington Primary School", road: "Main Street", postcodes: ["DE74 2"] }),
  "higham-on-the-hill": e({ name: "Higham on the Hill", phone: "01455 244 706", landmark: "St Peter's Church", road: "Main Street", postcodes: ["CV13 0"] }),
  hilton: e({ name: "Hilton", phone: "01283 890215", landmark: "Hilton Village Hall", road: "Main Street", postcodes: ["DE65 5"] }),
  hints: e({ name: "Hints", phone: "01827 802163", landmark: "Hints Hall", road: "School Lane", postcodes: ["B78 3"] }),
  hopwas: e({ name: "Hopwas", phone: "01827 802163", landmark: "The Red Lion", road: "Lichfield Road", postcodes: ["B78 3"] }),
  horninglow: e({ name: "Horninglow", phone: "01283 890215", landmark: "Horninglow Basin", road: "Horninglow Road", postcodes: ["DE13 0"] }),
  hoton: e({ name: "Hoton", phone: "01509 642158", landmark: "The Packe Arms", road: "Loughborough Road", postcodes: ["LE12 5"] }),
  hugglescote: e({ name: "Hugglescote", phone: "01530 654062", landmark: "The Gate Inn", road: "Ashby Road", postcodes: ["LE67 2"] }),
  ibstock: e({ name: "Ibstock", phone: "01530 654062", landmark: "Sence Valley Forest Park", road: "Melbourne Road", postcodes: ["LE67 6"] }),
  "isley-walton": e({ name: "Isley Walton", phone: "01509 642158", landmark: "All Saints Church", road: "Melbourne Road", postcodes: ["DE74 2"] }),
  kegworth: e({ name: "Kegworth", phone: "01509 642158", landmark: "Kegworth Village Hall", road: "High Street", postcodes: ["DE74 2"] }),
  "kings-newton": e({ name: "Kings Newton", phone: "01332 806148", landmark: "Kings Newton Hall", road: "Trent Lane", postcodes: ["DE73 8"] }),
  kingsbury: e({ name: "Kingsbury", phone: "01827 802163", landmark: "Kingsbury Water Park", road: "Tamworth Road", postcodes: ["B78 2"] }),
  "kirby-muxloe": e({ name: "Kirby Muxloe", phone: "01164 105069", landmark: "Kirby Muxloe Castle", road: "Mainfield Road", postcodes: ["LE9 2"] }),
  "lea-marston": e({ name: "Lea Marston", phone: "01827 802163", landmark: "Lea Marston Hotel", road: "Coton Road", postcodes: ["B76 0"] }),
  "leicester-forest-east": e({ name: "Leicester Forest East", phone: "01164 105069", landmark: "LFE Services", road: "Hinckley Road", postcodes: ["LE3 3"] }),
  leicestershire: e({ name: "Leicestershire", phone: "01530 654062", landmark: "Charnwood Forest", road: "The M1 Corridor", postcodes: ["LE67 3"] }),
  linton: e({ name: "Linton", phone: "01283 890215", landmark: "The Brickmakers Arms", road: "Main Street", postcodes: ["DE12 6"] }),
  lockington: e({ name: "Lockington", phone: "01509 642158", landmark: "St Nicholas Church", road: "Main Street", postcodes: ["DE74 2"] }),
  "long-whatton": e({ name: "Long Whatton", phone: "01509 642158", landmark: "The Falcon Inn", road: "Main Street", postcodes: ["LE12 5"] }),
  loughborough: e({ name: "Loughborough", phone: "01509 642158", landmark: "Loughborough University", road: "Market Place", postcodes: ["LE11 1"] }),
  lount: e({ name: "Lount", phone: "01530 654062", landmark: "The Ferrers Arms", road: "Nottingham Road", postcodes: ["LE65 1"] }),
  lullington: e({ name: "Lullington", phone: "01283 890215", landmark: "The Colvile Arms", road: "Main Street", postcodes: ["DE12 8"] }),
  mancetter: e({ name: "Mancetter", phone: "01827 802163", landmark: "St Peter's Church", road: "Manor Road", postcodes: ["CV9 1"] }),
  markfield: e({ name: "Markfield", phone: "01530 654062", landmark: "Hill Hole Quarry", road: "Main Street", postcodes: ["LE67 9"] }),
  "market-bosworth": e({ name: "Market Bosworth", phone: "01455 244 706", landmark: "Bosworth Country Park", road: "The Square", postcodes: ["CV13 0"] }),
  "marston-on-dove": e({ name: "Marston on Dove", phone: "01283 890215", landmark: "St Mary's Church", road: "Marston Lane", postcodes: ["DE65 5"] }),
  measham: e({ name: "Measham", phone: "01530 654062", landmark: "The Library", road: "High Street", postcodes: ["DE12 7"] }),
  melbourne: e({ name: "Melbourne", phone: "01332 806148", landmark: "Melbourne Hall", road: "High Street", postcodes: ["DE73 8"] }),
  middleton: e({ name: "Middleton", phone: "01827 802163", landmark: "Middleton Hall", road: "Church Lane", postcodes: ["B78 2"] }),
  "mile-oak": e({ name: "Mile Oak", phone: "01827 802163", landmark: "Mile Oak Community Centre", road: "Bonehill Road", postcodes: ["B78 3"] }),
  milton: e({ name: "Milton", phone: "01332 806148", landmark: "The Swan Inn", road: "Main Street", postcodes: ["DE65 6"] }),
  moira: e({ name: "Moira", phone: "01530 654062", landmark: "Moira Furnace", road: "Ashby Road", postcodes: ["DE12 6"] }),
  mountsorrel: e({ name: "Mountsorrel", phone: "01509 642158", landmark: "Mountsorrel Buttercross", road: "Market Place", postcodes: ["LE12 7"] }),
  nailstone: e({ name: "Nailstone", phone: "01455 244 706", landmark: "All Saints Church", road: "Rectory Lane", postcodes: ["CV13 0"] }),
  "nether-whitacre": e({ name: "Nether Whitacre", phone: "01827 802163", landmark: "The Gate Inn", road: "Station Road", postcodes: ["B46 2"] }),
  netherseal: e({ name: "Netherseal", phone: "01283 890215", landmark: "The Seal Inn", road: "Main Street", postcodes: ["DE12 8"] }),
  "newbold-coleorton": e({ name: "Newbold Coleorton", phone: "01530 654062", landmark: "The Cross Keys", road: "Ashby Road", postcodes: ["LE67 8"] }),
  "newbold-verdon": e({ name: "Newbold Verdon", phone: "01164 105069", landmark: "Newbold Verdon Hall", road: "Main Street", postcodes: ["LE9 9"] }),
  "newton-regis": e({ name: "Newton Regis", phone: "01827 802163", landmark: "The Queen's Head", road: "Main Street", postcodes: ["B79 0"] }),
  "newton-solney": e({ name: "Newton Solney", phone: "01283 890215", landmark: "Newton Park Hotel", road: "Main Street", postcodes: ["DE15 0"] }),
  "newtown-linford": e({ name: "Newtown Linford", phone: "01164 105069", landmark: "Bradgate Park", road: "Main Street", postcodes: ["LE6 0"] }),
  "no-mans-heath": e({ name: "No Mans Heath", phone: "01827 802163", landmark: "The Four Counties Inn", road: "Mercian Way", postcodes: ["B79 0"] }),
  "normanton-le-heath": e({ name: "Normanton le Heath", phone: "01530 654062", landmark: "The Packington Border", road: "Ashby Road", postcodes: ["LE67 2"] }),
  oadby: e({ name: "Oadby", phone: "01164 105069", landmark: "Leicester Racecourse", road: "The Parade", postcodes: ["LE2 5"] }),
  oakthorpe: e({ name: "Oakthorpe", phone: "01530 654062", landmark: "The Holly Bush", road: "Measham Road", postcodes: ["DE12 7"] }),
  odstone: e({ name: "Odstone", phone: "01455 244 706", landmark: "Odstone Hall", road: "Rayns Lane", postcodes: ["CV13 0"] }),
  osbaston: e({ name: "Osbaston", phone: "01455 244 706", landmark: "Osbaston Hall", road: "Lount Road", postcodes: ["CV13 0"] }),
  osgathorpe: e({ name: "Osgathorpe", phone: "01530 654062", landmark: "St Mary's Church", road: "Ashby Road", postcodes: ["LE12 9"] }),
  "over-whitacre": e({ name: "Over Whitacre", phone: "01827 802163", landmark: "The Swan Inn", road: "Nuneaton Road", postcodes: ["B46 2"] }),
  overseal: e({ name: "Overseal", phone: "01283 890215", landmark: "The Robin Hood Inn", road: "Burton Road", postcodes: ["DE12 6"] }),
  packington: e({ name: "Packington", phone: "01530 654062", landmark: "The Bull & Lion", road: "High Street", postcodes: ["LE65 1"] }),
  "peggs-green": e({ name: "Peggs Green", phone: "01530 654062", landmark: "The New Inn", road: "Nottingham Road", postcodes: ["LE67 8"] }),
  polesworth: e({ name: "Polesworth", phone: "01827 802163", landmark: "Polesworth Abbey", road: "Bridge Street", postcodes: ["B78 1"] }),
  prestwold: e({ name: "Prestwold", phone: "01509 642158", landmark: "Prestwold Hall", road: "Prestwold Lane", postcodes: ["LE12 5"] }),
  queniborough: e({ name: "Queniborough", phone: "01164 105069", landmark: "The Horse and Groom", road: "Main Street", postcodes: ["LE7 3"] }),
  quorn: e({ name: "Quorn", phone: "01509 447469", landmark: "Great Central Railway", road: "High Street", postcodes: ["LE12 8"] }),
  ratby: e({ name: "Ratby", phone: "01164 105069", landmark: "The Bull's Head", road: "Main Street", postcodes: ["LE6 0"] }),
  ravenstone: e({ name: "Ravenstone", phone: "01530 654062", landmark: "The Kings Arms", road: "Beeswax Lane", postcodes: ["LE67 2"] }),
  rearsby: e({ name: "Rearsby", phone: "01164 105069", landmark: "The Wheel Inn", road: "Melton Road", postcodes: ["LE7 4"] }),
  repton: e({ name: "Repton", phone: "01332 806148", landmark: "Repton School", road: "High Street", postcodes: ["DE65 6"] }),
  "rolleston-on-dove": e({ name: "Rolleston on Dove", phone: "01283 890215", landmark: "The Spread Eagle", road: "Burnside", postcodes: ["DE13 9"] }),
  rosliston: e({ name: "Rosliston", phone: "01283 890215", landmark: "Rosliston Forestry Centre", road: "Main Street", postcodes: ["DE12 8"] }),
  rothley: e({ name: "Rothley", phone: "01509 642158", landmark: "Rothley Court", road: "Woodgate", postcodes: ["LE7 7"] }),
  scropton: e({ name: "Scropton", phone: "01283 890215", landmark: "St John the Baptist Church", road: "Watery Lane", postcodes: ["DE65 5"] }),
  seagrave: e({ name: "Seagrave", phone: "01509 642158", landmark: "The White Horse", road: "Church Street", postcodes: ["LE12 7"] }),
  seckington: e({ name: "Seckington", phone: "01827 802163", landmark: "Seckington Castle Mound", road: "Church Lane", postcodes: ["B79 0"] }),
  shackerstone: e({ name: "Shackerstone", phone: "01455 244 706", landmark: "Battle of Bosworth Railway", road: "Station Road", postcodes: ["CV13 0"] }),
  shardlow: e({ name: "Shardlow", phone: "01332 806148", landmark: "The Clock Warehouse", road: "London Road", postcodes: ["DE72 2"] }),
  "sheepy-magna": e({ name: "Sheepy Magna", phone: "01455 244 706", landmark: "The Black Horse", road: "Main Street", postcodes: ["CV13 0"] }),
  "sheepy-parva": e({ name: "Sheepy Parva", phone: "01455 244 706", landmark: "Sheepy Mill", road: "Twycross Road", postcodes: ["CV13 0"] }),
  shellbrook: e({ name: "Shellbrook", phone: "01530 654062", landmark: "Ashby Road", road: "Ashby Road", postcodes: ["LE65 1"] }),
  shenton: e({ name: "Shenton", phone: "01455 244 706", landmark: "Bosworth Battlefield Heritage Centre", road: "Mill Lane", postcodes: ["CV13 0"] }),
  shepshed: e({ name: "Shepshed", phone: "01509 642158", landmark: "St Botolph's Church", road: "Market Place", postcodes: ["LE12 9"] }),
  shuttington: e({ name: "Shuttington", phone: "01827 802163", landmark: "The Wolferstan Arms", road: "Main Road", postcodes: ["B79 0"] }),
  sileby: e({ name: "Sileby", phone: "01509 642158", landmark: "Sileby Mill Marina", road: "High Street", postcodes: ["LE12 7"] }),
  sinope: e({ name: "Sinope", phone: "01530 654062", landmark: "The Moorlands", road: "A511", postcodes: ["LE67 8"] }),
  smisby: e({ name: "Smisby", phone: "01530 654062", landmark: "The Smisby Arms", road: "Main Street", postcodes: ["LE65 2"] }),
  snibston: e({ name: "Snibston", phone: "01530 654062", landmark: "Snibston Colliery Park", road: "Chiswell Drive", postcodes: ["LE67 3"] }),
  "stanton-under-bardon": e({ name: "Stanton under Bardon", phone: "01530 654062", landmark: "The Plough Inn", road: "Main Street", postcodes: ["LE67 9"] }),
  stapenhill: e({ name: "Stapenhill", phone: "01283 890215", landmark: "Stapenhill Gardens", road: "Main Street", postcodes: ["DE15 9"] }),
  "staunton-harold": e({ name: "Staunton Harold", phone: "01530 654062", landmark: "Staunton Harold Hall", road: "The Drive", postcodes: ["LE65 1"] }),
  "stenson-fields": e({ name: "Stenson Fields", phone: "01332 806148", landmark: "Stenson Bubble", road: "Stenson Road", postcodes: ["DE73 6"] }),
  "stoke-golding": e({ name: "Stoke Golding", phone: "01455 244 706", landmark: "St Margaret's Church", road: "High Street", postcodes: ["CV13 0"] }),
  stonydelph: e({ name: "Stonydelph", phone: "01827 802163", landmark: "Stonydelph Centre", road: "Pennine Way", postcodes: ["B77 4"] }),
  stretton: e({ name: "Stretton", phone: "01283 890215", landmark: "The Monks Bridge", road: "Main Street", postcodes: ["DE13 0"] }),
  "sutton-cheney": e({ name: "Sutton Cheney", phone: "01455 244 706", landmark: "Hercules Revived", road: "Main Street", postcodes: ["CV13 0"] }),
  "sutton-on-the-hill": e({ name: "Sutton on the Hill", phone: "01283 890215", landmark: "St Michael's Church", road: "Common Lane", postcodes: ["DE6 5"] }),
  swadlincote: e({ name: "Swadlincote", phone: "01283 890215", landmark: "Swadlincote Ski Centre", road: "High Street", postcodes: ["DE11 9"] }),
  swannington: e({ name: "Swannington", phone: "01530 654062", landmark: "Hough Mill", road: "Main Street", postcodes: ["LE67 8"] }),
  swithland: e({ name: "Swithland", phone: "01509 642158", landmark: "Swithland Woods", road: "Main Street", postcodes: ["LE12 8"] }),
  syston: e({ name: "Syston", phone: "01164 105069", landmark: "Syston Square", road: "High Street", postcodes: ["LE7 1"] }),
  tamworth: e({ name: "Tamworth", phone: "01827 802163", landmark: "Tamworth Castle", road: "Market Street", postcodes: ["B77 1", "B78 1", "B79 1"] }),
  tatenhill: e({ name: "Tatenhill", phone: "01283 890215", landmark: "St Michael's Church", road: "Main Street", postcodes: ["DE13 9"] }),
  thringstone: e({ name: "Thringstone", phone: "01530 654062", landmark: "Grace Dieu Priory", road: "Loughborough Road", postcodes: ["LE67 8"] }),
  thrussington: e({ name: "Thrussington", phone: "01509 642158", landmark: "The Star Inn", road: "The Green", postcodes: ["LE7 4"] }),
  thulston: e({ name: "Thulston", phone: "01332 806148", landmark: "The Harrington Arms", road: "Broad Lane", postcodes: ["DE72 3"] }),
  thurmaston: e({ name: "Thurmaston", phone: "01164 105069", landmark: "Thurmaston Shopping Centre", road: "Melton Road", postcodes: ["LE4 8"] }),
  ticknall: e({ name: "Ticknall", phone: "01332 806148", landmark: "Calke Abbey", road: "Main Street", postcodes: ["DE73 7"] }),
  tonge: e({ name: "Tonge", phone: "01530 654062", landmark: "Breedon Priory Golf Club", road: "Tonge Station Road", postcodes: ["DE73 8"] }),
  tutbury: e({ name: "Tutbury", phone: "01283 890215", landmark: "Tutbury Castle", road: "High Street", postcodes: ["DE13 9"] }),
  "two-gates": e({ name: "Two Gates", phone: "01827 802163", landmark: "Two Gates Ragged School", road: "Watling Street", postcodes: ["B77 1"] }),
  twycross: e({ name: "Twycross", phone: "01455 244 706", landmark: "Twycross Zoo", road: "Burton Road", postcodes: ["CV13 0"] }),
  ulverscroft: e({ name: "Ulverscroft", phone: "01164 105069", landmark: "Ulverscroft Priory", road: "Priory Lane", postcodes: ["LE67 9"] }),
  upton: e({ name: "Upton", phone: "01455 244 706", landmark: "Upton House", road: "A444", postcodes: ["CV13 0"] }),
  "walton-on-the-wolds": e({ name: "Walton on the Wolds", phone: "01509 642158", landmark: "The Anchor", road: "New Lane", postcodes: ["LE12 8"] }),
  "walton-on-trent": e({ name: "Walton on Trent", phone: "01283 890215", landmark: "The White Swan", road: "Main Street", postcodes: ["DE12 8"] }),
  wanlip: e({ name: "Wanlip", phone: "01164 105069", landmark: "Wanlip Hall", road: "Rectory Lane", postcodes: ["LE7 4"] }),
  warton: e({ name: "Warton", phone: "01827 802163", landmark: "The Office at Warton", road: "Church Road", postcodes: ["B79 0"] }),
  wellsborough: e({ name: "Wellsborough", phone: "01455 244 706", landmark: "Wellsborough Hall", road: "Bosworth Road", postcodes: ["CV13 0"] }),
  "weston-on-trent": e({ name: "Weston on Trent", phone: "01332 806148", landmark: "The Coopers Arms", road: "The Green", postcodes: ["DE72 2"] }),
  whitwick: e({ name: "Whitwick", phone: "01530 654062", landmark: "The Black Horse", road: "City of Dan", postcodes: ["LE67 5"] }),
  wigston: e({ name: "Wigston", phone: "01164 105069", landmark: "Wigston Framework Knitters Museum", road: "Leicester Road", postcodes: ["LE18 1"] }),
  willesley: e({ name: "Willesley", phone: "01530 654062", landmark: "Willesley Park Golf Club", road: "Willesley Road", postcodes: ["LE65 2"] }),
  willington: e({ name: "Willington", phone: "01332 806148", landmark: "Mercia Marina", road: "Twiggys Way", postcodes: ["DE65 6"] }),
  wilnecote: e({ name: "Wilnecote", phone: "01827 802163", landmark: "Wilnecote Station", road: "Watling Street", postcodes: ["B77 5"] }),
  wilson: e({ name: "Wilson", phone: "01530 654062", landmark: "The Bulls Head", road: "Main Street", postcodes: ["DE73 8"] }),
  winshill: e({ name: "Winshill", phone: "01283 890215", landmark: "Winshill Water Tower", road: "High Bank Road", postcodes: ["DE15 0"] }),
  witherley: e({ name: "Witherley", phone: "01455 244 706", landmark: "The Blue Lion", road: "Post Office Lane", postcodes: ["CV13 0"] }),
  woodhouse: e({ name: "Woodhouse", phone: "01509 642158", landmark: "St Mary in the Elms", road: "School Lane", postcodes: ["LE12 8"] }),
  "woodhouse-eaves": e({ name: "Woodhouse Eaves", phone: "01509 642158", landmark: "The Curzon Arms", road: "Maplewell Road", postcodes: ["LE12 8"] }),
  woodville: e({ name: "Woodville", phone: "01283 890215", landmark: "Woodville Clock Tower", road: "High Street", postcodes: ["DE11 7"] }),
  worthington: e({ name: "Worthington", phone: "01530 654062", landmark: "The Malt Shovel", road: "Main Street", postcodes: ["LE65 1"] }),
  wymeswold: e({ name: "Wymeswold", phone: "01509 642158", landmark: "The Three Crowns", road: "Far Street", postcodes: ["LE12 6"] })
}, S = [
  "/",
  "/about",
  "/services",
  "/reviews",
  "/faq",
  "/locations"
  // This is the main grid page you were looking at!
], r = [];
Object.keys(b).forEach((o) => {
  r.push(`/local-plumber/${o}/`), r.push(`/emergency-plumber/${o}/`), r.push(`/heating-engineer/${o}/`), r.push(`/drain-unblocking/${o}/`), r.push(`/leak-detection/${o}/`);
});
const E = [...S, ...r];
export {
  E as default
};
