import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const toAbsolute = (p) => path.resolve(__dirname, '..', p);

const base = 'https://rkm247.co.uk';

// 1. Locate the compiled SSR server entry bundle
let ssrPath = toAbsolute('dist/server/entry-server.cjs');
if (!fs.existsSync(ssrPath)) ssrPath = toAbsolute('dist/server/entry-server.js');
if (!fs.existsSync(ssrPath)) ssrPath = toAbsolute('dist/server/entry-server.mjs');

console.log(`📦 Loading SSR Bundle from: ${ssrPath}`);
const { render } = await import(ssrPath);

// 2. Load the dynamic routing configuration list array
const routesModule = await import(toAbsolute('dist-routes/ssg-routes.js'));
const allRoutes = routesModule.ssgRoutes || routesModule.default;

// Strip out standard resource files or wildcards
const routesToPrerender = allRoutes.filter(route => {
  return !path.basename(route).includes('.') && route !== '*';
});

(async () => {
  console.log(`\n🚀 RKM SEO Engine: Compiling ${routesToPrerender.length} distinct pages...\n`);

  // Read the master template generated by Vite's production client build pass
  const templateHtml = fs.readFileSync(toAbsolute('dist/client/index.html'), 'utf-8');

  for (const rawUrl of routesToPrerender) {
    let url = rawUrl;
    if (!url.startsWith('/')) url = '/' + url;
    if (url !== '/' && url.endsWith('/')) url = url.slice(0, -1);

    const cleanPath = url.replace(/^\/|\/$/g, '');
    const expectedCanonical = url === '/' ? `${base}/` : `${base}/${cleanPath}/`;

    // Fire the React server rendering architecture
    const { html: appHtml, helmet } = render(url);

    let finalHtml = templateHtml;

    // 3. ULTRA-AGGRESSIVE SANITIZATION (Busts data-rh duplicates completely)
    // This wipes out any existing tags with or without attributes/whitespace profiles
    finalHtml = finalHtml
      .replace(/<title[^>]*>[\s\S]*?<\/title>/gi, '')
      .replace(/<meta[^>]*name=["']description["'][^>]*>/gi, '')
      .replace(/<meta[^>]*property=["']og:title["'][^>]*>/gi, '')
      .replace(/<meta[^>]*property=["']og:description["'][^>]*>/gi, '')
      .replace(/<meta[^>]*property=["']og:url["'][^>]*>/gi, '')
      .replace(/<link[^>]*rel=["']canonical["'][^>]*>/gi, '')
      .replace(/<script[^>]*type=["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi, '')
      .replace('<html lang="en">', '<html lang="en-GB">');

    // 4. METADATA RE-INJECTION
    const seoTags = [
      helmet?.title?.toString() || '',
      helmet?.meta?.toString() || '',
      `<link rel="canonical" href="${expectedCanonical}" />`,
      helmet?.script?.toString() || ''
    ].join('\n    ').trim();

    // Safely embed headers and root application layouts using flexible regex
    finalHtml = finalHtml
      .replace(/<\/head>/i, `    ${seoTags}\n</head>`)
      .replace(/<div\s+id=["']root["']><\/div>/i, `<div id="root">${appHtml}</div>`);

    // 5. FILE WRITER SYSTEM
    const outputDir = url === '/' ? 'dist/client' : `dist/client/${cleanPath}`;
    const outputFile = path.join(outputDir, 'index.html');

    fs.mkdirSync(toAbsolute(outputDir), { recursive: true });
    fs.writeFileSync(toAbsolute(outputFile), finalHtml, 'utf-8');

    console.log(`✅ SEO Baked Successfully: /${cleanPath}/`);
  }

  console.log('\n🎉 Core Pre-render Phase Finished.\n');
})();