import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const toAbsolute = (p) => path.resolve(__dirname, '..', p);

const base = 'https://rkm247.co.uk';

// 1. Target the server bundle generated by your server configuration file
let ssrPath = toAbsolute('dist/server/entry-server.cjs');
if (!fs.existsSync(ssrPath)) {
  ssrPath = toAbsolute('dist/server/entry-server.js');
}
if (!fs.existsSync(ssrPath)) {
  ssrPath = toAbsolute('dist/server/entry-server.mjs');
}

console.log(`📦 Loading SSR Bundle from: ${ssrPath}`);
const { render } = await import(ssrPath); 

// Load your SSG static route manifest
const routesModule = await import(toAbsolute('dist-routes/ssg-routes.js'));
const allRoutes = routesModule.ssgRoutes || routesModule.default;

// Filter out broken inputs and asset patterns
const routesToPrerender = allRoutes.filter(route => {
    return !path.basename(route).includes('.') && route !== '*';
});

(async () => {
  console.log(`\n🚀 RKM SEO Engine: Prerendering ${routesToPrerender.length} clean pages...\n`);

  for (const rawUrl of routesToPrerender) {
    // FIXED: Enforce absolute leading slash formatting on the URL string 
    // before passing it to the server bundle to guarantee perfect metadata extraction
    let url = rawUrl;
    if (!url.startsWith('/')) {
      url = '/' + url;
    }
    if (url !== '/' && url.endsWith('/')) {
      url = url.slice(0, -1);
    }

    const cleanPath = url.replace(/^\/|\/$/g, '');
    const expectedCanonical = url === '/' ? `${base}/` : `${base}/${cleanPath}/`;
    
    // Execute the React Server Render bundle using the explicitly normalized path string
    const { html: appHtml, helmet } = render(url);

    // Read freshly inside the loop from dist/client/index.html to capture Vite's production compiled JS asset paths automatically
    let finalHtml = fs.readFileSync(toAbsolute('dist/client/index.html'), 'utf-8');

    // 2. SANITIZATION: Clean out default metadata placeholders to prevent duplication
    finalHtml = finalHtml
      .replace(/<title>.*?<\/title>/gi, '')
      .replace(/<meta[^>]*name=["']description["'][^>]*>/gi, '')
      .replace(/<link[^>]*rel=["']canonical["'][^>]*>/gi, '')
      .replace(/<script[^>]*type=["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi, '')
      .replace('<html lang="en">', '<html lang="en-GB">');

    // 3. INJECTION: Bake in unique SEO headers from React Helmet
    const seoTags = `
    ${helmet?.title?.toString() || ''}
    ${helmet?.meta?.toString() || ''}
    <link rel="canonical" href="${expectedCanonical}" />
    ${helmet?.script?.toString() || ''}
    `;

    finalHtml = finalHtml
      .replace('</head>', `${seoTags}\n</head>`)
      .replace('<div id="root"></div>', `<div id="root">${appHtml}</div>`);

    // 4. DIRECTORY LAYOUT WRITER
    const outputDir = url === '/' ? 'dist/client' : `dist/client/${cleanPath}`;
    const outputFile = path.join(outputDir, 'index.html');

    fs.mkdirSync(toAbsolute(outputDir), { recursive: true });
    fs.writeFileSync(toAbsolute(outputFile), finalHtml);
    
    console.log(`✅ SEO Baked: /${cleanPath}/`);
  }
  
  console.log('\n🎉 Build Complete. All pages compiled successfully.\n');
})();